# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_mail', models.CharField(max_length=50)),
                ('account_cet4', models.IntegerField(default=0)),
                ('account_cet4_today', models.IntegerField(default=0)),
                ('account_cet6', models.IntegerField(default=0)),
                ('account_cet6_today', models.IntegerField(default=0)),
                ('account_counter', models.IntegerField(default=100)),
                ('account_time', models.DateField(default=django.utils.timezone.now)),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cet4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet4_num', models.IntegerField()),
                ('cet4_word', models.CharField(max_length=30)),
                ('cet4_describe', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cet6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet6_num', models.IntegerField()),
                ('cet6_word', models.CharField(max_length=30)),
                ('cet6_describe', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('custom_num', models.IntegerField()),
                ('custom_catalog', models.IntegerField(default=django.utils.timezone.now)),
            ],
        ),
    ]
