# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_mail',
            new_name='account_nickname',
        ),
        migrations.AlterField(
            model_name='cet4',
            name='cet4_describe',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cet6',
            name='cet6_describe',
            field=models.CharField(max_length=200),
        ),
    ]
