# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_mail',
            new_name='account_nickname',
        ),
    ]
