# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180625_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_setting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_time',
            field=models.DateField(default=datetime.datetime(2018, 6, 24, 15, 50, 38, 899936)),
        ),
    ]
